AdminPageinMVC/Controllers/HomeworkController.cs
using AdminPageinMVC.Data;
using AdminPageinMVC.Dto;
using AdminPageinMVC.Entity;
using AdminPageinMVC.OnlyModelViews;
using AdminPageinMVC.Repository;
using AdminPageinMVC.Repository.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPageinMVC.Controllers;

public class HomeworkController : Controller
{
    private readonly AppDbContext _context;
    private readonly IHomeworkRepository _homeworkRepository;

    public HomeworkController(IHomeworkRepository homeworkRepository, AppDbContext context)
    {
        _homeworkRepository = homeworkRepository;
        _context = context;
    }

    public async Task<IActionResult> GetAllHomework()
    {
        var homework =  await _homeworkRepository.GetAllHomeworkAsync();
        return View("_HomeworkPage", homework);
    }

    public async Task<IActionResult> AddHomework() => View("_AddHomework");

    [HttpPost]
    public async Task<ActionResult> AddHomework(AddHomeworkDto addHomeworkDto)
    {
        if (!ModelState.IsValid) return View("_HomeworkPage");
        var homework = new HomeworkDTO();
        homework.ImageUrl = addHomeworkDto.ImageUrl;
        homework.Description = addHomeworkDto.Description;
        var findTask = await _context.Task.FirstOrDefaultAsync(c => c.Id == addHomeworkDto.TaskId);
        if (findTask != null) homework.Task = findTask;
        await _homeworkRepository.AddHomeworkAsync(homework);
        var allListHomework = await _homeworkRepository.GetAllHomeworkAsync();
        return View("_HomeworkPage", allListHomework);
    }
    public async Task<IActionResult> GetByIdHomework(int id)
    {
        var teacherByIdAsync = await _homeworkRepository.GetHomeworkByIdAsync(id); 
        return View("_ByIdHomework", teacherByIdAsync);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateHomework(int id, AddHomeworkDto addHomeworkDto)
    {
        if (!ModelState.IsValid) return View("_HomeworkPage");
        var homeworkDto = new HomeworkDTO();
        homeworkDto.ImageUrl = addHomeworkDto.ImageUrl;
        homeworkDto.Description = addHomeworkDto.Description;
        var findTask = await _context.Task.FirstOrDefaultAsync(c => c.Id == addHomeworkDto.TaskId);
        if (findTask != null) homeworkDto.Task = findTask;
        await _homeworkRepository.UpdateHomeworkAsync(id, homeworkDto);
        var allListHomework = await _homeworkRepository.GetAllHomeworkAsync();
        return View("_HomeworkPage", allListHomework);
    }
    public async Task<IActionResult> DeleteHomework(int id)
    {
        await _homeworkRepository.DeleteHomeworkAsync(id);
        var allListHomework = await _homeworkRepository.GetAllHomeworkAsync();
        return View("_HomeworkPage", allListHomework);
    }
}

AdminPageinMVC/Views/Homework/_AddHomework.cshtml
@{
    Layout = "~/Views/Shared/_Homework.cshtml";
}
<form class="update-form" method="post" action="@Url.Action("AddHomework", "Homework")">
    <input type="text" name="imageUrl" class="input" placeholder="ImageUrl" required />
    <input type="text" name="description" class="input" placeholder="Description" required />
    <input type="text" name="taskId" class="input" placeholder="Task Id" required />
    <div class="btns">
        <button class="confirm" type="submit">Confirm</button>
        <button method="get" asp-controller="Homework" asp-action="GetAllHomework" class="cancel">Cancel</button>
    </div>
</form>

AdminPageinMVC/Views/Homework/_ByIdHomework.cshtml
@model AdminPageinMVC.Dto.HomeworkDTO
@{
    Layout = "~/Views/Shared/_Homework.cshtml";
}
<form action="@Url.Action("UpdateHomework", "Homework")" method="post">
    <input type="hidden" name="id" value="@Model.Id" />

    <div>
        <input class="input" type="text" id="Name" name="imageUrl" placeholder="Image Url" value="@Model.ImageUrl" />
    </div>

    <div>
        <input class="input" type="text" id="description" name="description" placeholder="Description" value="@Model.Description" />
    </div>
    <div>
        <input class="input" type="text" id="taskId" name="taskId" placeholder="Task Id" value="@Model.Task.Id" />
    </div>
    <div>
        <button type="submit" style="margin-top:20px" class="confirm">Update</button>
    </div>
</form>

AdminPageinMVC/Views/Homework/_HomeworkPage.cshtml
@model List<AdminPageinMVC.Dto.HomeworkDTO>
@{
    Layout = "~/Views/Shared/_Homework.cshtml";
}
<table class="user-table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Img Url</th>
            <th>Description</th>
            <th>Task Id</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var homework in Model)
        {
            <tr>
                <form action="@Url.Action("UpdateHomework", "Homework")" method="post">
                <td>
                    <span>@homework.Id</span>
                </td>
                <td>
                    <span class="view-mode">@homework.ImageUrl</span>
                    <input type="text" class="edit-mode hide" name="img" value="@homework.ImageUrl" />
                    <input type="hidden" name="id" value="@homework.Id" />
                </td>
                <td>
                    <span class="view-mode">@homework.Description</span>
                    <input type="text" class="edit-mode hide" name="description" value="@homework.Description" />
                </td>
                <td>
                    <span class="view-mode">@homework.Task.Id</span>
                    <input type="text" class="edit-mode hide" name="taskId" value="@homework.Task.Id" />
                </td>
                <td>
                    <a class="btn-update">Update</a>
                    <button class="btn-confirm hide" asp-controller="Homework" asp-action="UpdateHomework" type="submit">Confirm</button>
                    <button class="btn-delete" asp-controller="Homework" asp-action="DeleteHomework" type="submit">Delete</button>
                    <a class="btn-cancel hide">Cancel</a>
                </td>
                </form>
            </tr>
        }
    </tbody>
</table>

<div class="center-align">
    <a class="waves-effect waves-light btn" href="@Url.Action("AddHomework", "Homework")">Create New Education</a>
</div>