AdminPageinMVC/Controllers/ResultController.cs
using AdminPageinMVC.Entity;
using AdminPageinMVC.OnlyModelViews;
using AdminPageinMVC.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdminPageinMVC.Controllers;

public class ResultController : Controller
{
    private readonly IResultRepository _resultRepository;
    private readonly IEducationRepository _educationRepository;
    private readonly IUserRepository _userRepository;

    public ResultController(IResultRepository resultRepository, IEducationRepository educationRepository, IUserRepository userRepository)
    {
        _resultRepository = resultRepository;
        _educationRepository = educationRepository;
        _userRepository = userRepository;
    }

    public async Task<IActionResult> GetResults()
    {
        var allResult = await _resultRepository.GetAllResultAsync();

        return View("ResultTable", allResult);
    }

    public async Task<IActionResult> AddResult()
    {
        ViewBag.EducationList = await _educationRepository.GetAllEducationAsync();
        ViewBag.UserList = await _userRepository.GetAllUsersAsync();

        return View("AddResult");
    }
    [HttpPost]
    public async Task<IActionResult> AddResult(AddResultDto addResultDto)
    {
        if (!ModelState.IsValid) return View("ResultTable");
        Result result = new Result();
        result.Url = addResultDto.Url;
        result.User = await _userRepository.GetUserByIdAsync(addResultDto.UserId);
        result.Education = await _educationRepository.GetEducationByIdAsync(addResultDto.EducationId);
        await _resultRepository.AddResultAsync(result);
        var allResultAsync = await _resultRepository.GetAllResultAsync();
        return View("ResultTable", allResultAsync);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateResult(int id, AddResultDto addResultDto)
    {
        if (!ModelState.IsValid) return View("ResultTable");
        var result = await _resultRepository.GetResultByIdAsync(id);
        result.Url = addResultDto.Url;
        result.Education = await _educationRepository.GetEducationByIdAsync(addResultDto.EducationId);
        result.User = await _userRepository.GetUserByIdAsync(addResultDto.UserId);
        await _resultRepository.UpdateResultAsync(result);
        var all = await _resultRepository.GetAllResultAsync();
        return View("ResultTable", all);
    }
    public async Task<IActionResult> UpdateResult() => View("GetById");

    [HttpPost]
    public async Task<IActionResult> GetResultById(int id)
    {
        if (!ModelState.IsValid) return View("ResultTable");
        var resultByIdAsync = await _resultRepository.GetResultByIdAsync(id);
        ViewBag.EducationList = await _educationRepository.GetAllEducationAsync();
        ViewBag.UserList = await _userRepository.GetAllUsersAsync();
        return View("UpdateResult", resultByIdAsync);
    }

    public async Task<IActionResult> DeleteResult() => View("DeleteResult");

    [HttpPost]
    public async Task<IActionResult> DeleteResult(int id)
    {
        if (!ModelState.IsValid) return View("ResultTable");
        await _resultRepository.DeleteResultAsync(id);
        var all = await _resultRepository.GetAllResultAsync();
        return View("ResultTable", all);
    }
}

AdminPageinMVC/Views/Result/AddResult.cshtml
@{
    Layout = "~/Views/Shared/_Result.cshtml";
}

<head>
    <style>
		option {
			background: #1f1f1f;
			color: white;
		}
	</style>
</head>

<form method="post" asp-action="AddResult" asp-controller="Result">
    <div class="update-form">
        <label for="educationId">Education:</label>
        <select class="form-control" id="educationId" name="educationId" required style="background:none; color:white; padding:5px; margin-left:5px; margin-bottom:10px">
            <option value="">Select an education</option>
            @foreach (var education in ViewBag.EducationList)
            {
                <option value="@education.Id">@education.Title</option>
            }
        </select>
    </div>
    <div class="update-form">
        <label for="userId">User:</label>
        <select class="form-control" id="userId" name="userId" required style="background:none; color:white; padding:5px; margin-left:5px; margin-bottom:10px">
            <option value="">Select a user</option>
            @foreach (var user in ViewBag.UserList)
            {
                <option value="@user.Id">@user.FullName</option>
            }
        </select>
    </div>
    <div class="update-form">
        <label for="url">URL:</label>
        <input type="text" class="input" id="url" name="url" required>
    </div>
    <button type="submit" class="confirm">Add Result</button>
</form>

AdminPageinMVC/Views/Result/DeleteResult.cshtml
@{
    Layout = "~/Views/Shared/_Result.cshtml";
}

<form class="user__course" method="post" action="@Url.Action("DeleteResult", "Result")">
    <input type="text" name="id" placeholder="Result id" class="get__inptut" />
    <button class="confirm" type="submit">Delete</button>
</form>

AdminPageinMVC/Views/Result/GetById.cshtml
@{
    Layout = "~/Views/Shared/_Result.cshtml";
}

<form class="user__course" method="post" action="@Url.Action("GetResultById", "Result")">
    <input type="text" name="id" placeholder="Result id" class="get__inptut" />
    <button class="confirm" type="submit">Get</button>
</form>

AdminPageinMVC/Views/Result/ResultTable.cshtml
@model List<AdminPageinMVC.Entity.Result>
@{
    Layout = "~/Views/Shared/_Result.cshtml";
}
<table class="user-table">
    <thead>
    <tr>
        <th>Id</th>
        <th>URL</th>
        <th>Education Title</th>
        <th>User Full Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var result in Model)
    {
        <tr>
            <td>@result.Id</td>
            <td>@result.Url</td>
            <td>@result.Education.Title</td>
            <td>@result.User.FullName</td>
        </tr>
    }
    </tbody>
</table>

AdminPageinMVC/Views/Result/UpdateResult.cshtml
@model AdminPageinMVC.Entity.Result
@{
    Layout = "~/Views/Shared/_Result.cshtml";
}
<head>
    <style>
        option {
            background: #1f1f1f;
            color: white;
        }
    </style>
</head>

<form method="post" asp-action="UpdateResult" asp-controller="Result">
    <div class="update-form">
        <input type="hidden" name="id" value="@Model.Id" /> 
        <label for="educationId">Education:</label>
        <select class="form-control" id="educationId" name="educationId" required style="background:none; color:white; padding:5px; margin-left:5px; margin-bottom:10px">
            <option value="@Model.Education.Id">@Model.Education.Title</option>
            @foreach (var education in ViewBag.EducationList)
            {
                if (education.Title != Model.Education.Title)
                {
                    <option value="@education.Id">@education.Title</option>
                }
            }
        </select>
    </div>
    <div class="update-form">
        <label for="userId">User:</label>
        <select class="form-control" id="userId" name="userId" required style="background:none; color:white; padding:5px; margin-left:5px; margin-bottom:10px">
            <option value="@Model.User.Id">@Model.User.FullName</option>
            @foreach (var user in ViewBag.UserList)
            {
                if (user.FullName != Model.User.FullName)
                {
                    <option value="@user.Id">@user.FullName</option>
                }
            }
        </select>
    </div>
    <div class="update-form">
        <label for="url">URL:</label>
        <input type="text" class="input" id="url" name="url" value="@Model.Url" required>
    </div>
    <button type="submit" class="confirm">Update Result</button>
</form>