AdminPageinMVC/Controllers/EducationController.cs
using AdminPageinMVC.Data;
using AdminPageinMVC.Dto;
using AdminPageinMVC.OnlyModelViews;
using AdminPageinMVC.Repository;
using AdminPageinMVC.Repository.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPageinMVC.Controllers;

public class EducationController : Controller
{
    private readonly IEducationRepository _educationRepository;
    private readonly AppDbContext _context;
    public EducationController(IEducationRepository educationRepository, AppDbContext context)
    {
        _educationRepository = educationRepository;
        _context = context;
    }

    public async Task<ActionResult> GetAllEducation()
    {
        var education = await _educationRepository.GetAllEducationAsync();
        return View("_EducationPage", education);
    }

    public async Task<IActionResult> AddEducation() => View("_AddEducation");   

    [HttpPost]
    public async Task<ActionResult> AddEducation(AddEducationDto educationDto)
    {
        if (!ModelState.IsValid) return View("_EducationPage");
        var edu = new EducationDTO();
        edu.Title = educationDto.Title;
        edu.End = educationDto.End;
        edu.Description = educationDto.Description;
        var findCourse = await _context.Course.FirstOrDefaultAsync(c => c.Id == educationDto.CourseId);
        if (findCourse != null)
        {
            edu.Course = findCourse;
        }

        await _educationRepository.AddEducationAsync(edu);
        var getEducationList = await _educationRepository.GetAllEducationAsync();
        return View("_EducationPage", getEducationList);
    }
    public async Task<IActionResult> GetByIdEducation(int id)
    {
        var teacherByIdAsync = await _educationRepository.GetEducationByIdAsync(id);
        return View("_ByIdEducation", teacherByIdAsync);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateEducation(int id, AddEducationDto educationDto)
    {
        if (!ModelState.IsValid) return View("_EducationPage");
        var education = new EducationDTO();
        education.Title = educationDto.Title;
        education.End = educationDto.End;
        education.Description = educationDto.Description;
        var findCourse = await _context.Course.FirstOrDefaultAsync(c => c.Id == educationDto.CourseId);
        if (findCourse != null)
        {
            education.Course = findCourse;
        }
        await _educationRepository.UpdateEducationAsync(id, education);
        var allListTeachers = await _educationRepository.GetAllEducationAsync();
        return View("_EducationPage", allListTeachers);
    }
    public async Task<IActionResult> DeleteCourse(int id)
    {
        await _educationRepository.DeleteEducationAsync(id);
        var allListTeachers = await _educationRepository.GetAllEducationAsync();
        return View("_EducationPage", allListTeachers);
    }

}

AdminPageinMVC/Controllers/LessonController.cs
using AdminPageinMVC.Data;
using AdminPageinMVC.Dto;
using AdminPageinMVC.Entity;
using AdminPageinMVC.OnlyModelViews;
using AdminPageinMVC.Repository;
using AdminPageinMVC.Repository.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPageinMVC.Controllers;

public class LessonController : Controller
{
      private readonly ILessonRepository _lessonRepository;
      private readonly AppDbContext _context;
      public LessonController(ILessonRepository lessonRepository, AppDbContext context)
      {
          _lessonRepository = lessonRepository;
          _context = context;
      }

      public async Task<ActionResult> GetAllLesson()
      {
          var lesson = await _lessonRepository.GetAllLessonAsync();
          return View("_LessonPage", lesson);
      }
    public async Task<IActionResult> AddLesson() => View("_AddLesson");

      [HttpPost]
      public async Task<IActionResult> AddLesson(AddLessonDto addLessonDto)
      {
          if (string.IsNullOrWhiteSpace(addLessonDto.Title) || string.IsNullOrWhiteSpace(addLessonDto.VideoUrl) || string.IsNullOrWhiteSpace(addLessonDto.Information))
          {
              ModelState.AddModelError("", "All fields must be filled");
              return View("_LessonPage");
          }
          var lesson = new LessonDTO();
          lesson.Title = addLessonDto.Title;
          lesson.VideoUrl = addLessonDto.VideoUrl;
          lesson.Information = addLessonDto.Information;
            var findCourse = await _context.Course.FirstOrDefaultAsync(c => c.Id == addLessonDto.CourseId);
        if (findCourse != null) lesson.Course = findCourse;
        await _lessonRepository.AddLessonAsync(lesson);
        var getLessonList = await _lessonRepository.GetAllLessonAsync();
        return View("_LessonPage", getLessonList);
      }



    public async Task<IActionResult> GetByIdEducation(int id)
      {
          var teacherByIdAsync = await _lessonRepository.GetLessonByIdAsync(id);
          return View("_ByIdLesson", teacherByIdAsync);
      }
    [HttpPost]
    public async Task<IActionResult> UpdateLesson(int id, AddLessonDto addLessonDto)
      {
          if (!ModelState.IsValid) return View("_LessonPage");
          var lesson = new LessonDTO();
        lesson.Title = addLessonDto.Title;
        lesson.VideoUrl = addLessonDto.VideoUrl;
        lesson.Information = addLessonDto.Information;
        var findCourse = await _context.Course.FirstOrDefaultAsync(c => c.Id == addLessonDto.CourseId);
          if (findCourse != null)
          {
              lesson.Course = findCourse;
          }
          await _lessonRepository.UpdateLessonAsync(id, lesson);
          var allListLesson = await _lessonRepository.GetAllLessonAsync();
          return View("_LessonPage", allListLesson);
    }

    public async Task<IActionResult> DeleteLesson(int id)
    {
        await _lessonRepository.DeleteLessonAsync(id);
        var allListTeachers = await _lessonRepository.GetAllLessonAsync();
        return View("_LessonPage", allListTeachers);
    }

}

AdminPageinMVC/Views/Education/_AddEducation.cshtml
@{
    Layout = "~/Views/Shared/_Education.cshtml";
}
<form class="update-form" method="post" action="@Url.Action("AddEducation", "Education")">
    <input type="text" name="title" class="input" placeholder="Title" required />
    <input type="text" name="end" class="input" placeholder="End" required />
    <input type="text" name="description" class="input" placeholder="Description" required />
    <input type="text" name="courseId" class="input" placeholder="Course Id" required />
    <div class="btns">
        <button class="confirm" type="submit">Confirm</button>
        <button method="get" asp-controller="Lesson" asp-action="GetAllLesson" class="cancel">Cancel</button>
    </div>
</form>

AdminPageinMVC/Views/Education/_ByIdEducation.cshtml
@model AdminPageinMVC.Entity.Education
@{
    Layout = "~/Views/Shared/_Education.cshtml";
}
<form action="@Url.Action("UpdateEducation", "Education")" method="post">
    <input type="hidden" name="id" value="@Model.Id" />

    <div>
        <input class="input" type="text" id="Name" name="title" placeholder="Title" value="@Model.Title" required />
    </div>

    <div>
        <input class="input" type="text" id="ImgUrl" name="name" placeholder="End" value="@Model.End" required />
    </div>

    <div>
        <input class="input" type="text" id="Type" name="description" placeholder="Description" value="@Model.Description" required />
    </div>

    <div>
        <button type="submit" style="margin-top:20px" class="confirm">Update</button>
    </div>
</form>

AdminPageinMVC/Views/Education/_DeleteEducation.cshtml
@{
    Layout = "~/Views/Shared/_Education.cshtml";
}

<form class="user__result" method="post" action="@Url.Action("DeleteCourse", "Education")">
    <input type="text" name="id" placeholder="Education id" class="get__inptut" required />
    <button class="confirm" type="submit">Delete</button>
</form>

AdminPageinMVC/Views/Education/_EducationPage.cshtml
@model List<AdminPageinMVC.Dto.EducationDTO>
@{
    Layout = "~/Views/Shared/_Education.cshtml";
}

<div class="user-table">
    @(Html
        .Grid(Model) 
        .Build(columns =>
        {
            columns.Add(model => model.Id).Titled("Id").Filterable(true).Sortable(true);
            columns.Add(model => model.Title).Titled("Title").Filterable(true).Sortable(true);
            columns.Add(model => model.End).Titled("End").Filterable(true).Sortable(true);
            columns.Add(model => model.Description).Titled("Description").Filterable(true).Sortable(true);
            columns.Add(model => model.Course.Id).Titled("Course Id").Filterable(true).Sortable(true);
            columns.Add()
                .Encoded(false)
                .RenderedAs(model =>
                {
                    return $@"
                        <a class=""btn-update"">Update</a>
                        <button class=""btn-confirm hide"" asp-controller=""Education"" asp-action=""UpdateEducation"" type=""submit"">Confirm</button>
                        <button class=""btn-delete"" asp-controller=""Education"" asp-action=""DeleteCourse"" type=""submit"">Delete</button>
                        <a class=""btn-cancel hide"">Cancel</a>
                    ";
                })
                .Titled("Actions");
        })
)
</div>

<div class="center-align">
    <a class="waves-effect waves-light btn" href="@Url.Action("AddEducation", "Education")">Create New Education</a>
</div>

AdminPageinMVC/Views/Education/_UpdateEducationInfo.cshtml
@model AdminPageinMVC.Dto.EducationDTO
@{
    Layout = "~/Views/Shared/_Education.cshtml";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update User</title>
    <style>
        /* Your CSS code here */
        .update-form {
            display: flex;
            flex-direction:column;
            gap:20px;
            justify-content:center;
            align-items:center;
            margin: 10px;
        }

        .input {
            width: 100%;
            padding: 5px;
            border: 1px solid #ddd;
            border-radius: 4px;
            display:flex;
            flex-direction: column;
            gap: 10px;
        }

        .btn-confirm{
            background-color: green; /* Adjust colors as needed */
            border: none;
            color: white;
            cursor: pointer;
            padding: 5px 10px;
            margin-right: 5px;
        }
        .btn-cancel {
            background-color: red; /* Adjust colors as needed */
            border: none;
            color: white;
            cursor: pointer;
            padding: 5px 10px;
            margin-right: 5px;
        }
    </style>
</head>
<body>
<form class="update-form" method="post" action="@Url.Action("UpdateEducation", "Education")">
    <input type="hidden" name="id" value="@Model.Id" />
    <input type="text" name="title" value="@Model.Title" class="input" />
    <input type="text" name="end" value="@Model.End" class="input" />
    <input type="text" name="description" value="@Model.Description" class="input" />
    <input type="text" name="courseId" value="@Model.Course.Id" class="input" />
    <button class="btn-confirm" type="submit">Confirm</button>
    <button class="btn-cancel">Cancel</button>
</form>
</body>